[server]
port = 7860
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#003399"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fc"
textColor = "#1e293b"
font = "sans serif"
